### ISSUE TITLE
Issue with Fonts and GUI Elements & Weird build errors when compiling in Release

### ISSUE THREAD

**Issue by Pitj3** [GameFoundry/bsf#146] opened 2018-06-10 00:03 UTC
Back with another issue,

Running DX build of the framework (latest version)
code is here: https://hastebin.com/osukigepit.cpp

The font I'm loading is from the examples data GUI folder

Error I'm getting:
Run-Time Check Failure #2 - Stack around the variable 'skin' was corrupted.
https://i.imgur.com/03Osb25.png

Without loading a custom font I get this:
https://i.imgur.com/7q2VAoM.png

No clue where to go from here with this. First time I've ever encountered it.
When running in release the error is of course incomprehensible.
https://i.imgur.com/4oQxg1M.png

Building in Release causes these errors:
https://i.imgur.com/fZHjb5l.png
I have to hit rebuild all to get rid of them.

Next to that I always have these errors:
https://i.imgur.com/0WoLJEM.png

But they don't matter for the build, everything keeps running fine. might just be a setting in my visual studio though.

Hope this makes sense to you and it's on my side that I'm doing something wrong.

Sorry for reporting so many issues but I really like working with your framework and would like to keep going without ripping out my hairs ;)

**Comment by Pitj3** [comment] 2018-06-10 13:32
Actually did a complete reinstall of my PC today, including all code related software.
After recompiling the latest version of the framework, and using the latest version of VS 2017.
Still get this error:
https://i.imgur.com/KzfhNo2.png

and the list of other errors before:
https://i.imgur.com/GfBXIaf.png

Running Windows SDK 10.0.17134.0
VS 2017 Community Version 15.7.3

**Comment by BearishSun** [comment] 2018-06-10 13:36
Thanks. Could you also post your `CMakeLists.txt` file, could be something related to the build configuration.

**Comment by Pitj3** [comment] 2018-06-10 13:37
cmake_minimum_required (VERSION 3.9.0)
project (bsf)

set (BSF_SOURCE_DIR ${PROJECT_SOURCE_DIR}/Source)
set (APP_ROOT_DIR ${PROJECT_SOURCE_DIR})
set (BS_IS_BANSHEE3D 0)

# Default install dir
if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
	if(LINUX)
		set(CMAKE_INSTALL_PREFIX /usr/local/opt/bsf CACHE PATH "..." FORCE)
	endif()
endif()

include(Source/CMake/Properties.cmake)
include(Source/CMake/FindPackageOrBuild.cmake)
include(Source/CMake/HelperMethods.cmake)

add_subdirectory(Source)

**Comment by Pitj3** [comment] 2018-06-10 13:39
I was not able to run the install command in cmake btw, giving me errors
https://hastebin.com/eseqimapih.txt

**Comment by BearishSun** [comment] 2018-06-10 13:41
That looks like the CMake file for `bsf` itself, do you not have one for your own project? If not, how are setting up the project for your executable - just adding a new VS project manually?

The `install` command requires to be run with elevated permission if you are installing to `C:/Program Files`. You can run the command prompt with administrator privileges, or change the install dir to a non-system location.

**Comment by Pitj3** [comment] 2018-06-10 13:42
Ye I just create a new VS project, and copy over the libraries, headers and dll's and set them up in VS.

**Comment by Pitj3** [comment] 2018-06-10 13:44
Install with elevated permissions was succesful

**Comment by Pitj3** [comment] 2018-06-10 13:45
In case you are wondering, I link against just the compiled bsf.lib (for the appropriate version (debug or release)) and give the environment a path to the appropriate dll's.

**Comment by BearishSun** [comment] 2018-06-10 13:49
I'm guessing some C++ compiler flags do not get set on the executable project, but they are enabled when the `bsf` library itself got compiled, and it's confusing the compiler. I'll see if I can track down exactly which.

**Comment by Pitj3** [comment] 2018-06-10 13:57
Compiler flags would be logical for the errors I get in my intellisense. But compiler flags for the stack error?

**Comment by Pitj3** [comment] 2018-06-10 13:57
Hope you can find the issue. Let me know if you need anything from me. I’m happy to help!

**Comment by BearishSun** [comment] 2018-06-10 14:00
While I'm tracking this down, you could try setting up a "Link with binaries" CMake build as described here: https://www.bsframework.io/docs/build.html

And see if a VS solution/project generated from that has the same issue.

**Comment by BearishSun** [comment] 2018-06-10 14:13
I've tried creating a new plain VS project and linking with bsf directly and I cannot reproduce the issue. I am missing the textures/meshes you are importing in your project however, which could be contributing to the issue. 

Ideally, could you upload your entire project? If not, could you try commenting out parts of the code related to ground/box/sky and see if you can reproduce the same issue without them? If you can't upload the entire project I'd appeciate just having the VS project/solution itself, so I can verify the compile flags.

**Comment by Pitj3** [comment] 2018-06-10 14:20
When creating a project with cmake following the instructions you posted I don't have the errors any more. And it compiles all fine in Debug. In release I can compile but get an exception:
https://i.imgur.com/5BugXzf.png

Here is the VS project I created myself:
https://mega.nz/#!lJYFADKD!nDd3wrE3HK40acXXXhH9s_9dQPkRBgIcL4BMobjTv4c

**Comment by Pitj3** [comment] 2018-06-10 14:29
Same goes for the cmake project btw, debug runs fine.
Release now gives an even less descriptive error:
https://i.imgur.com/9pU65Dj.png

**Comment by Pitj3** [comment] 2018-06-10 14:31
Disabling my Avast resulted in this:
https://i.imgur.com/5Sa03Fn.png

With this error:
https://i.imgur.com/bb3k7Ow.png

Hope some of this is making sense to you

**Comment by BearishSun** [comment] 2018-06-10 14:57
Thanks for uploading your project. I'm able to reproduce the issue with your project, but not with my own, even though they appear nearly identical. I do wonder how did you include the entire 'dependenices' folder as part of the VS project? That's not how I'm used to handling includes/libraries/binaries in a VS project, and it's the only difference I can see between our projects.

I'll check the release mode error later, it's possibly unrelated since it happens in the CMake build as well.

**Comment by Pitj3** [comment] 2018-06-10 14:59
I include the files in the VC Directories. I just add the paths there so the compiler knows where to find the files

**Comment by Pitj3** [comment] 2018-06-10 15:32
Both release and debug work fine on my own (non cmake) project now!
The only issue is the IntelliSense errors, and possibly the cmake release version although I don't use that. But others might run into that issue

**Comment by BearishSun** [comment] 2018-06-10 15:56
Glad you got it sorted. The release mode crash in the CMake version was most likely caused by Debug .dlls being present next to the executable, rather than Release mode ones (getting the same error if I do that, but otherwise it runs fine).

I'm not sure what to do about those IntelliSense errors. They seem to happen in both Debug and Release mode, in CMake and non-CMake projects. All I can suggest is disabling them in the Output window, IntelliSense is full of false positives anyway (I always keep the Output window limited to build errors). Linking with source appears to be the only way to avoid them. Since I doubt there is any proper way to get rid of them, I'll close the issue since the rest of the problems are resolved.

**Closed by BearishSun** 2018-06-10 15:56 UTC
