### ISSUE TITLE
Create multiple fbx model with animation problem

### ISSUE THREAD

**Issue by MNodesadsad** [GameFoundry/bsf#316] opened 2019-05-01 16:10 UTC
Hi, I don't know how to speak English, So I hope you can understand(haha。I am use bsf 1.1.0 Windows 64-bit Binaries + vs2017 on Win10, I want to create some SceneObject with fbx mesh and play animation on scene(such as my demo will create 16 SceneObjects),  and the fbx file is your sample's Drone.fbx。

the problem is when I run the demo, sometimes some drone SceneObject are not visible on scene,  please run the demo multiple times, and this is my code(please help me (´,,•ω•,,‘) )
[DemoSources.zip](https://github.com/GameFoundry/bsf/files/3135104/DemoSources.zip):

#include "BsApplication.h"
#include "Scene/BsSceneObject.h"
#include "Components/BsCCamera.h"
#include "Components/BsCRenderable.h"
#include "Components/BsCSkybox.h"
#include "Components/BsCAnimation.h"
#include "Material/BsMaterial.h"
#include "Resources/BsBuiltinResources.h"
#include "Importer/BsImporter.h"
#include "Importer/BsTextureImportOptions.h"
#include "Importer/BsMeshImportOptions.h"
#include "Mesh/BsMesh.h"
#include "Resources/BsResources.h"
#include "BsCameraFlyer.h"                    //this is your sample's BsCameraFlyer.h file

class MyApplication : public bs::Application
{
  struct DroneModelAssets 
  {
	  bs::HMesh mesh;
	  bs::HAnimationClip animClip;
	  bs::HMaterial material;
  };

  public:
	MyApplication(const bs::START_UP_DESC& desc)
		:Application(desc)
	{ 

	}

 private:
	void onStartUp() override
	{
		using namespace bs;
		Application::onStartUp();

		setupInputConfig();

		addCamera(Vector3(0, 0, 10), Vector3::ZERO);
		addSkybox(loadSkyboxTexture());

		//create generateDroneCount count drone model
		//but you can see, when you run the demo, maybe has not generateDroneCount count drone model on scene
		//please run the demo multiple times
		DroneModelAssets droneModelAssets = loadDroneModelAssets();
		constexpr int generateDroneCount = 16;
		for (int i = 0; i != generateDroneCount; ++i) 
		{
			Vector3 position = Vector3(-generateDroneCount / 2.0f + i, 0.0f, 0.0f);

			//if set addDroneModel function animationEnableCull parameter false, then demo has not problem
			//is this message helpful for you ? I don't know what happened...
			addDroneModel(droneModelAssets, position, true);
		}
	}

	bs::HCamera addCamera(const bs::Vector3 &position, const bs::Vector3 &lookAtLocation) 
	{
		using namespace bs;

		HSceneObject sceneCameraSO = SceneObject::create("SceneCamera");
		sceneCameraSO->setPosition(position);
		sceneCameraSO->lookAt(lookAtLocation);

		sceneCameraSO->addComponent<CameraFlyer>();

		HCamera sceneCamera = sceneCameraSO->addComponent<CCamera>();
		sceneCamera->setProjectionType(PT_PERSPECTIVE);
		sceneCamera->setNearClipDistance(0.001f);
		sceneCamera->setFarClipDistance(1000);
		sceneCamera->getViewport()->setTarget(Application::instance().getPrimaryWindow());
		sceneCamera->getViewport()->setClearColorValue(Color(0.001f, 0.001f, 0.001f));

		const SPtr<RenderSettings>& renderSettings = sceneCamera->getRenderSettings();
		renderSettings->enableIndirectLighting = true;

		sceneCamera->setRenderSettings(renderSettings);

		return sceneCamera;
	}

	bs::HSceneObject addSkybox(const bs::HTexture &skyboxTexture) 
	{
		using namespace bs;
		
		HSceneObject skyboxSO = SceneObject::create("Skybox");
		HSkybox skybox = skyboxSO->addComponent<CSkybox>();
		skybox->setTexture(skyboxTexture);

		return skyboxSO;
	}

	bs::HSceneObject addDroneModel(const DroneModelAssets &droneModelAssets,
	  const bs::Vector3 &position, bool animationEnableCull)
	{
		using namespace bs;

		HSceneObject droneSO = SceneObject::create("Drone");
		droneSO->setPosition(position);
	
		HRenderable cubeRenderable = droneSO->addComponent<CRenderable>();
		cubeRenderable->setMesh(droneModelAssets.mesh);
		cubeRenderable->setMaterial(droneModelAssets.material);

		HAnimation animation = droneSO->addComponent<CAnimation>();
		animation->setEnableCull(animationEnableCull);
		animation->play(droneModelAssets.animClip);
	
		return droneSO;
	}

	bs::HTexture loadSkyboxTexture() 
	{
		using namespace bs;

		SPtr<TextureImportOptions> textureOptions = Importer::instance().createImportOptions<TextureImportOptions>("assets/rathaus.hdr");
		textureOptions->setIsCubemap(true);
		textureOptions->setSRGB(false);
		textureOptions->setGenerateMipmaps(true);
		textureOptions->setFormat(PF_RG11B10F);
		textureOptions->setCubemapSourceType(CubemapSourceType::Cylindrical);

		return gImporter().import<Texture>("assets/rathaus.hdr", textureOptions);
	}

	DroneModelAssets loadDroneModelAssets() 
	{
		using namespace bs;

		SPtr<MeshImportOptions> importOptions = MeshImportOptions::create();
		importOptions->setImportSkin(true);
		importOptions->setImportAnimation(true);

		HMesh droneMesh;
		HAnimationClip droneAnimClip;
		Vector<SubResource> resources = gImporter().importAll("assets/drone.fbx", importOptions);
		for (auto &entry : resources)
		{
			if (rtti_is_of_type<Mesh>(entry.value.get()))
				droneMesh = static_resource_cast<Mesh>(entry.value);
			else if (rtti_is_of_type<AnimationClip>(entry.value.get()))
				droneAnimClip = static_resource_cast<AnimationClip>(entry.value);
		}

		return DroneModelAssets { droneMesh, droneAnimClip, loadDroneMaterial() };
	}

	bs::HMaterial loadDroneMaterial() 
	{
		using namespace bs;

		HShader shader = gBuiltinResources().getBuiltinShader(BuiltinShader::Standard);
		HTexture albedoTex = loadDroneModelTexture("assets/drone_diff.jpg", true);
		HTexture normalTex = loadDroneModelTexture("assets/drone_normal.jpg", false);
		HTexture roughnessTex = loadDroneModelTexture("assets/drone_rough.jpg", false);
		HTexture metalnessTex = loadDroneModelTexture("assets/drone_metal.jpg", false);

		HMaterial material = Material::create(shader);
		material->setTexture("gAlbedoTex", albedoTex);
		material->setTexture("gNormalTex", normalTex);
		material->setTexture("gRoughnessTex", roughnessTex);
		material->setTexture("gMetalnessTex", metalnessTex);

		return material;
	}

	bs::HTexture loadDroneModelTexture(const char *path, bool isSRGB) 
	{
		using namespace bs;

		SPtr<TextureImportOptions> textureOptions = Importer::instance().createImportOptions<TextureImportOptions>(path);
		textureOptions->setSRGB(isSRGB);
		textureOptions->setGenerateMipmaps(true);

		return gImporter().import<Texture>(path, textureOptions);
	}

	void setupInputConfig()
	{
		using namespace bs;

		auto inputConfig = gVirtualInput().getConfiguration();
		inputConfig->registerButton("Forward", BC_W);
		inputConfig->registerButton("Back", BC_S);
		inputConfig->registerButton("Left", BC_A);
		inputConfig->registerButton("Right", BC_D);
		inputConfig->registerButton("Forward", BC_UP);
		inputConfig->registerButton("Back", BC_DOWN);
		inputConfig->registerButton("Left", BC_LEFT);
		inputConfig->registerButton("Right", BC_RIGHT);
		inputConfig->registerButton("FastMove", BC_LSHIFT);
		inputConfig->registerButton("RotateObj", BC_MOUSE_LEFT);
		inputConfig->registerButton("RotateCam", BC_MOUSE_RIGHT);

		inputConfig->registerAxis("Horizontal", VIRTUAL_AXIS_DESC((UINT32)InputAxis::MouseX));
		inputConfig->registerAxis("Vertical", VIRTUAL_AXIS_DESC((UINT32)InputAxis::MouseY));
	}

};

int main()
{
	using namespace bs;
	VideoMode videoMode(1280, 720);
	Application::startUp<MyApplication>(videoMode, "MyApplication", false);
	Application::instance().runMainLoop();
	Application::shutDown();
	return 0;
}

**Comment by BearishSun** [comment] 2019-05-02 11:11
Hi.

 I have tried creating an equivalent example to yours, and I am not seeing issues with the drone rendering. It is possible you are seeing an issue that was fixed since v1.1.0 release. You can try grabbing a  recent nightly build from [here](https://www.bsframework.io/download.html), or compiling the framework manually. Perhaps that fixes the problem.

I should also note that the camera flyer is very fast compared to the drone model size. It's easy to hit a movement key and move out of the range of drones making them be out of view.

**Comment by MNodesadsad** [comment] 2019-05-02 12:44
Hi, I am currently using the latest Nightly version, and now should create more drone model,  until out of camera viewport range, such as 50 in my demo, and then run demo, you move the camera can see , maybe has not 50 visible drone model in scene....
![W52X@319XNQU(ORDE`G@FDG](https://user-images.githubusercontent.com/18095795/57075884-b8e36b80-6d1a-11e9-86d5-301d362548b9.png)
![Y48@T$C18{{F84NL35_6H}0](https://user-images.githubusercontent.com/18095795/57075906-d0225900-6d1a-11e9-822c-efd0d6c0cc43.png)

**Comment by BearishSun** [comment] 2019-05-02 13:32
Thank you, I was able to reproduce the problem in release mode. I'll let you know when it's resolved.

**Comment by BearishSun** [comment] 2019-05-09 07:21
The issue should be resolved on latest master, fixed in ce3d722ac5253212514e0813920a0351a86ba4d5.

If the problem is still occurring feel free to re-open the issue.

**Closed by BearishSun** 2019-05-09 07:21 UTC
Labels: type: bug
